[pytest]
addopts = --cov=src/pemjh/function_tools --cov=src/pemjh/numbers --cov-report=term-missing --doctest-modules --durations=0 -m "not regression and not example" --showlocals
markers =
        example: Example from the website.
        regression: Tests that run to produce the desired answer but may well be slow.
testpaths = tests